class_name TeemoSentence


const CODINGS = [
  "Kita lakukan satu-satu, ya!",
  "Kalau mau main, harus nyalain dulu.",
  "Pertama duduk, lalu belajar.",
  "Makan dulu, baru main.",
  "Kalau mau nyanyi, pencet tombol dulu.",
  "Kita tekan tombol, baru lampunya nyala.",
  "Gambar dulu, warnai nanti.",
  "Jalan dulu, lompat nanti.",
  "Urut, nggak boleh loncat-loncat!",
  "Komputernya nurut sama perintah kita.",
  "Ayo kita susun langkahnya!",
  "Satu, dua, tiga… urut, ya!",
  "Komputer suka langkah rapi.",
  "Kalau kacau, nanti salah!",
  "Ganti baju dulu, baru keluar rumah.",
  "Kita nyalain komputer dulu, baru bisa main game.",
  "Buka mata, duduk, lalu bangun!",
  "Cuci tangan dulu, lalu makan.",
  "Kalau kita ikutin urutan, semua lancar!",
  "Langkah-langkah harus berbaris.",
  "Satu per satu ya, jangan bareng!",
  "Peluk dulu, baru bobo.",
  "Kalau salah urutan, nanti bingung.",
  "Pencet ini dulu, baru itu.",
  "Jalan pelan-pelan, satu kaki dulu.",
  "Kalau mau bikin gambar, mulainya dari kepala.",
  "Main game-nya ikutin langkahnya ya.",
  "Komputer cuma ngerti urutan.",
  "Buka buku dulu, baru baca.",
  "Ayo kita ikutin cara mainnya.",
  "Bikin jus? Kupas dulu buahnya.",
  "Nyalakan lampu dulu sebelum cari mainan.",
  "Susun balok dari bawah dulu.",
  "Naik tangga juga satu-satu, kan?",
  "Komputer nggak bisa lompat-lompat.",
  "Langkah pertama itu penting banget!",
  "Kita mulai dari awal, ya.",
  "Jangan loncat ke akhir dulu.",
  "Cuci tangan → ambil sendok → makan!",
  "Urutan itu kayak baris upacara.",
  "Buka pintu dulu, baru keluar.",
  "Pasang sepatu dulu, baru lari.",
  "Jalan ke kiri dulu, baru ke kanan.",
  "Kalau kita bingung, cek langkahnya.",
  "Ikutin urutan supaya berhasil!",
  "Kita simpan mainan dulu, baru tidur.",
  "Nyalakan TV dulu, baru nonton.",
  "Masak nasi? Cuci beras dulu.",
  "Urutan itu kayak main ular tangga.",
  "Kita lari dulu, lalu istirahat.",
  "Sikat gigi dulu, baru bobo.",
  "Langkah-langkahnya jangan ditukar.",
  "Kalau ikutin urutan, semua senang!",
  "Komputer butuh langkah yang pas.",
  "Kita ajari komputer, satu langkah per satu.",
  "Jangan loncat-loncat, nanti jatuh!",
  "Ayo main game: pencet → lompat → senyum!",
  "Ikutin petunjuknya ya!",
  "Yuk kita susun rapi dulu.",
  "Ambil kertas dulu, lalu gambar.",
  "Ikutin arah panahnya!",
  "Semua harus sesuai giliran.",
  "Main piano? Tekan nada dari awal.",
  "Gunting dulu, lalu tempel.",
  "Komputer ikut yang kita tulis duluan.",
  "Urutan itu penting banget!",
  "Masukkan nama dulu, baru bisa main.",
  "Main game itu kayak naik tangga.",
  "Satu-satu, jangan buru-buru.",
  "Mau minum susu? Ambil gelas dulu.",
  "Langkahnya seperti cerita: awal, tengah, akhir!",
  "Kita ajak komputer main bareng, tapi harus urut.",
  "Susun lego dari dasar dulu.",
  "Komputer bingung kalau urutannya salah.",
  "Kita kasih tahu komputer pakai langkah-langkah.",
  "Ayo bikin urutan untuk mandi!",
  "Urutan itu kayak nyanyi lagu.",
  "Kita ikuti urutan supaya hasilnya bagus.",
  "Duduk dulu, lalu makan permen.",
  "Komputer belajar dari urutan yang kita buat.",
  "Kalau semua urut, kerja jadi mudah.",
  "Main air habis mandi, bukan sebelum.",
  "Mainan ini bisa disusun satu-satu.",
  "Jangan bolak-balik langkahnya ya.",
  "Komputer nurut sama yang pertama ditulis.",
  "Kalau mau jalan-jalan, siapin tas dulu.",
  "Kita pelan-pelan, urut satu-satu.",
  "Ayo buat cerita berurutan.",
  "Mulai dari awal, biar ngerti semuanya.",
  "Jangan lewati langkah penting.",
  "Komputer nggak bisa tebak, harus urut.",
  "Kayak main masak-masakan: aduk dulu, baru sajikan.",
  "Main robot? Programnya harus urut!",
  "Cuci tangan, ambil sabun, bilas, selesai!",
  "Kalau salah urutan, robotnya bingung.",
  "Mau nyanyi? Pencet tombol lagu dulu.",
  "Mau jalan-jalan? Pakai sepatu dulu.",
  "Kita main puzzle, mulai dari sudut ya!",
  "Cerita seru harus dimulai dari awal.",
  "Ayo jadi pemandu urutan yang hebat!"
]

const OBSERVINGS = [
  "Ayo lihat dulu sebelum ambil!",
  "Hmm, apa ya yang salah di sini?",
  "Yuk perhatikan dulu!",
  "Lihat-lihat dulu, jangan buru-buru.",
  "Mata lihat, otak mikir.",
  "Ada yang aneh, yuk cari!",
  "Diam sebentar, lihat sekeliling.",
  "Wah, apa ya yang hilang?",
  "Kita cari petunjuk dulu, yuk!",
  "Lihat warnanya, beda nggak?",
  "Ayo amati dulu sebelum menjawab.",
  "Jangan langsung sentuh, lihat dulu.",
  "Ayo tebak, apa yang terjadi?",
  "Coba lihat bentuknya, sama nggak?",
  "Matanya dipakai, telinganya dengar.",
  "Ada petunjuknya loh, cari yuk!",
  "Hmm, mana ya yang cocok?",
  "Lihat gambar ini, ada apa ya?",
  "Sebelum menjawab, lihat dulu ya.",
  "Wah, ada yang sembunyi! Cari yuk!",
  "Coba perhatikan dulu, baru pilih.",
  "Ada perbedaan kecil, lihat baik-baik!",
  "Temukan yang salah yuk!",
  "Apa yang hilang di sini?",
  "Jangan asal nebak ya, lihat dulu.",
  "Yuk, lihat pelan-pelan.",
  "Coba cocokkan dulu gambarnya.",
  "Sebelum memecahkan, kita amati dulu!",
  "Coba lihat, petunjuknya di mana ya?",
  "Ayo cari tahu bareng-bareng.",
  "Jangan langsung jawab, lihat lagi.",
  "Coba ingat apa yang kamu lihat tadi.",
  "Ayo temukan jawabannya dengan melihat.",
  "Lihat semua sudutnya, ya!",
  "Yuk pelototin dulu semuanya!",
  "Hmm, bagian mana yang berubah?",
  "Mata tajam, otak pintar!",
  "Lihat posisi benda-bendanya, yuk!",
  "Cari yang beda sendiri!",
  "Wah, yang ini nggak sama!",
  "Sebelum mulai, kita amati dulu.",
  "Coba hitung dulu ya.",
  "Gambar ini ada rahasianya!",
  "Yuk temukan mana yang salah.",
  "Kita pakai mata detektif!",
  "Jangan terburu-buru, sabar dan lihat.",
  "Lihat pelan-pelan, biar nggak salah.",
  "Perhatikan warnanya deh.",
  "Lihat dengan teliti yuk.",
  "Wah, yang ini kebalik ya?",
  "Kamu lihat apa tadi?",
  "Petunjuknya kecil, tapi penting!",
  "Yuk jadi si mata jeli!",
  "Lihat dan bandingkan yuk.",
  "Ayo temukan jawabannya dari gambar!",
  "Ssst... lihat dulu sebelum mulai.",
  "Coba perhatikan arah panahnya!",
  "Gambar ini ada teka-tekinya!",
  "Cari dan temukan ya!",
  "Amati dulu baru pilih ya.",
  "Temukan benda yang beda yuk!",
  "Wah, warnanya berubah!",
  "Gambar ini aneh ya?",
  "Coba perhatikan angka-angkanya.",
  "Yuk lihat pelan-pelan.",
  "Hmm, yang mana yang hilang ya?",
  "Benda ini ada di mana ya?",
  "Coba cocokkan bayangannya!",
  "Ayo temukan gambar tersembunyi.",
  "Lihat garis-garisnya dulu.",
  "Yang ini lebih besar nggak?",
  "Bentuknya beda, kamu lihat?",
  "Perhatikan, mana yang cocok?",
  "Jangan klik dulu, lihat semuanya!",
  "Gambar ini bisa bicara loh!",
  "Kamu lihat monster kecilnya?",
  "Coba cari jalan yang benar.",
  "Petunjuknya ada di gambar!",
  "Benda mana yang nggak cocok?",
  "Kita harus teliti ya!",
  "Coba lihat dari dekat.",
  "Yuk amati perubahannya.",
  "Bentuknya mirip, tapi nggak sama!",
  "Siap jadi detektif cilik?",
  "Ayo cari perbedaannya!",
  "Yang ini ada berapa jumlahnya?",
  "Gambar ini aneh nggak?",
  "Perhatikan susunannya, yuk!",
  "Kita harus sabar dan teliti.",
  "Mata harus jeli kayak kucing!",
  "Gambar ini berubah, coba lihat!",
  "Petunjuknya ada di warna!",
  "Coba ingat gambarnya tadi!",
  "Yuk temukan jawabannya dengan mata!",
  "Apa kamu lihat yang aku lihat?",
  "Yang ini hilang satu ya?",
  "Urutannya salah, kamu tahu?",
  "Kita cari tahu bareng yuk!",
  "Kamu jeli sekali kalau lihat ini!",
  "Lihat... lihat... baru kerjakan, ya!"
]

static func random_coding_sentence() -> String:
	return CODINGS[randi_range(0, CODINGS.size() - 1)]

static func random_observing_sentence() -> String:
	return OBSERVINGS[randi_range(0, OBSERVINGS.size() - 1)]
